# Generated by Django 5.0.13 on 2025-03-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Camper Care', 'Camper Care'), ('Unit Head', 'Unit Head'), ('Counselor', 'Counselor')], max_length=255, null=True),
        ),
    ]
