# Generated by Django 5.0.13 on 2025-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.BooleanField(default=False, verbose_name='Profile Complete'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Camper Care', 'Camper Care'), ('Unit Head', 'Unit Head'), ('Counselor', 'Counselor')], default='', max_length=255),
        ),
    ]
