services:
  docs:
    image: bunk_logs_local_docs
    container_name: bunk_logs_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bunk_logs:/app/bunk_logs:z
    ports:
      - '9000:9000'
    command: /start-docs
