# Generated by Django 5.0.13 on 2025-03-12 03:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BunkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('not_on_camp', models.BooleanField(default=False)),
                ('social_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('behavior_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('participation_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('request_camper_care_help', models.BooleanField(default=False)),
                ('request_unit_head_help', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bunk_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bunk_logs', to='campers.camperbunkassignment')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bunk log',
                'verbose_name_plural': 'bunk logs',
                'ordering': ['-date'],
                'unique_together': {('bunk_assignment', 'date')},
            },
        ),
    ]
